
name: Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: eu-central-1
    steps:
      - uses: actions/checkout@v3
      - name: Build the project wit node
        run: |
          npm install
          npm run build
          cd build
          aws s3 cp . s3://cgn-aws-monitoring-example-bucket/ --acl public-read --recursive    
